apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-oke-app
  namespace: oracle
spec:
  selector:
    matchLabels:
      app: node-oke-app
  replicas: 3
  template:
    metadata:
      labels:
        app: node-oke-app
    spec:
      containers:
      - name: node-oke-app
        image: iad.ocir.io/idkkibu1oc3i/oke-apps/node-oke-app:${BUILDRUN_HASH}
        imagePullPolicy: Always
        ports:
        - name: node-oke-app
          containerPort: 3000
          protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: node-oke-app-svc
  namespace: oracle
spec:
  selector:
    app: node-oke-app
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-oke-app-ing
  namespace: oracle
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: node-oke-app-svc
              port:
                number: 3000
